/**
 * * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  docs: [{
      type: 'doc',
      id: 'welcome',
    },
    {
      type: 'doc',
      id: 'overview',
    },
    {
      type: "category",
      label: 'Getting Started',

      link: {
          type: "doc",
          id:'getting_started/getting_started'

      },
      items: [
          {
              type: "doc",
              id: "getting_started/nodejs",
              label: 'Nodejs'
          },
          {
              type: "doc",
              id: "getting_started/python",
              label: 'Python'
          },
          {
              type: "doc",
              id: "getting_started/rust",
              label: 'Rust'
          },
      ]
    },
    {
      type: 'category',
      label: 'Libraries',
      collapsed: false,
      items: [{
          type: 'doc',
          id: 'libraries/overview',
          label: 'Overview',
        },

        {
          type: 'category',
          label: 'Rust',
          items: [
            {
              type: 'category',
              label: 'How To',
              items: [
                {
                  type: 'category',
                  label: 'Account Manager',
                  items: [
                    {
                      type: 'doc',
                      id: 'libraries/rust/how_to/account_manager/create_accounts',
                      label: 'Create Accounts',
                    },
                  ]
                },
                {
                  type: 'category',
                  label: 'Account',
                  items: [
                    {
                      type: 'doc',
                      id: 'libraries/rust/how_to/account/generate_list_addresses',
                      label: 'Generate And List Addresses',
                    },
                  ]
                }
              ]
            },
            {
              type: 'doc',
              id: 'libraries/rust/api_reference',
              label: 'API Reference'
            },
          ]
        },
        {
          type: 'category',
          label: 'Node.js',
          items: [
            {
              type: "category",
              label: "How To",
              items:[
                  {
                      type: 'autogenerated',
                      dirName: 'libraries/nodejs/how_to'
                  },
              ]
            },
            {
              type: 'doc',
              id: 'libraries/nodejs/exchange_guide',
              label: 'Exchange Guide'
            },
            {
              type: 'category',
              label: 'API Reference',
              items:[
                {
                    type: "doc",
                    id: "libraries/nodejs/references/api_ref",
                    label: 'API Reference'
                },
                {
                    type: "category",
                    label: "Classes",
                    items:[
                        {
                            type: 'autogenerated',
                            dirName: 'libraries/nodejs/references/classes'
                        },
                    ]
                },
                {
                    type: "category",
                    label: "Enums",
                    items:[
                        {
                            type: 'autogenerated',
                            dirName: 'libraries/nodejs/references/enums'
                        },
                    ]
                },
                {
                    type: "category",
                    label: "Interfaces",
                    items:[
                        {
                            type: 'autogenerated',
                            dirName: 'libraries/nodejs/references/interfaces'
                        },
                    ]
                },
            ]
            },
          ]
        },
        {
          type: 'category',
          label: 'Python',
          items: [
            {
              type: "category",
              label: "How To",
              items:[
                  {
                      type: 'autogenerated',
                      dirName: 'libraries/python/how_to'
                  },
              ]
            },
            {
              type: 'doc',
              id: 'libraries/python/api_reference',
              label: 'API Reference'
            }
          ]
        }
      ]
    },
    {
      type: 'doc',
      id: 'troubleshooting',
      label: 'Troubleshooting'
    },
    {
      type: 'doc',
      id: 'contribute',
      label: 'Contribute',
    }
  ]
};